apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: grpc-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 443
        name: grpc
        protocol: GRPC
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ingress-grpc
spec:
  hosts:
    - "*"
  gateways:
    - grpc-gateway
  http:
    - match:
      - uri:
          prefix: /pb.Streamsvc
      route:
      - destination:
          host: streamsvc
          port:
            number: 8000
    - match:
      - uri:
          prefix: /pb.Foosvc
      route:
      - destination:
          host: foosvc
          port:
            number: 8000
    - match:
      - uri:
          prefix: /pb.Addsvc
      route:
      - destination:
          host: addsvc
          port:
            number: 8000
